game:
    name: Centipede
    module: centipede
    number_of_steps: 5
type: InMemory
oracle:
    name: OpenSpielMLP
    capacity:
        input_size: 1
        output_size: 2
        nn_depth: 3
        nn_width: 3
    file_path: centipede_alpha_zero
collector:
    number_of_processes: 1
    mcts:
        number_of_simulations: 1
        pucb_constant: 1.0
        discount_factor: 1.0
        dirichlet_alpha: 0.3
        dirichlet_weight: 0.25
    max_buffer_length: 100
    number_of_episodes: 1
    temperature_schedule:
        - [0, 1.0]
trainer:
    batch_size: 32
    max_training_epochs: 1
    early_stop_loss: 1e-3
    learning_rate: 1e-3
    loading_workers: 1
report_generator:
    oracle_led_players: ['O']
    number_of_tests: 100
    buckets:
        - [-inf, 0.20]
        - [0.20, 0.40]
        - [0.40, 0.60]
        - [0.60, 0.80]
        - [0.80, +inf]
number_of_epochs: 1
evaluation_episodes: 100
max_old_models: 10
hdf5_path_prefix: centipede_data
server_hostname: 127.0.0.1
server_port: 8888
workspace_path: test_workspace
manual_play:
    manual_player: 'O'
    autonomous_policy:
        name: DeterministicOraclePolicy
