game:
    name: MCTSTicTacToe 
    first_player: random
type: InMemory
oracle:
    name: SimpleMLP
    module: simple_mlp
    input_size: 18
    output_size: 9
    file_path: tic_tac_toe_alpha_zero_custom_oracle
collector:
    number_of_processes: 1
    mcts:
        number_of_simulations: 1
        pucb_constant: 1.0
        pucb_increase: 0.0
        discount_factor: 1.0
        dirichlet_alpha: 0.3
        dirichlet_weight: 0.25
    max_buffer_length: 100
    number_of_episodes: 1
    temperature_schedule:
        - [0, 1.0]
trainer:
    batch_size: 32
    max_training_epochs: 1
    early_stop_loss: 1e-3
    learning_rate: 1e-3
    loading_workers: 1
report_generator:
    number_of_tests: 100
    buckets:
        - [-inf, 0.25]
        - [0.25, 0.75]
        - [0.75, +inf]
    policies:
        X:
            name: RandomPolicy
        O:
            name: DeterministicOraclePolicy
            oracle: TrainedOracle
number_of_epochs: 1
evaluation:
    episodes: 100
    max_models: 10
    uncertainty_penalty_coefficient: 3.0
    discount_factor: 1.0
    policy:
        name: DeterministicOraclePolicy
    true_skill:
        mu: 25.0
        sigma: 8.333
        beta: 1.476
        tau: 0.0
        draw_probability: 0.1
hdf5_path_prefix: tic_tac_toe_data_custom_oracle
server_hostname: 127.0.0.1
server_port: 8888
workspace_path: test_workspace
manual_play:
    manual_player: 'O'
    autonomous_policy:
        name: DeterministicOraclePolicy
